import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { client } from "../utils/createClient";
import { D1Database } from "@cloudflare/workers-types";

interface Env {
  NORTHWIND_DB: D1Database;
}

export const getServerSideProps = async (context: any) => {
  const ps = context.env.NORTHWIND_DB.prepare("SELECT * from users");
  const dbData = await ps.first();

  const getData = async () => {
    const data = await client.get({
      endpoint: "blog",
    });
    return data.contents;
  };
  return {
    props: {
      runtime: process.env.NEXT_RUNTIME,
      uuid: await fetch("https://uuid.rocks/plain").then((response) =>
        response.text()
      ),
      data: await getData(),
      dbData,
    },
  };
};

const Home: NextPage<{
  runtime: string;
  uuid: string;
  data: any[];
  dbData: any;
}> = ({ runtime, uuid, data, dbData }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://nextjs.org">Next.js, running at the {runtime}!</a>
        </h1>

        <div>
          <pre>{dbData.toSting()}</pre>
        </div>

        <div>
          {data.map((item: any) => {
            return (
              <div key={item.id}>
                <h1>{item.title}</h1>
              </div>
            );
          })}
        </div>

        <p className={styles.description}>
          Here&apos;s a server-side UUID:
          <code className={styles.code}>{uuid}</code>
        </p>
      </main>
    </div>
  );
};

export default Home;
